services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://MYusername:DB%210nope%21@cluster0.8cwg8bx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=mysecretkey
    depends_on:
      - "mongo"
  frontend:
    build: ./Frontend/frontend
    ports:
      - 5173:5173
